# json types
OBJECT = "OBJECT"
ARRAY = "ARRAY"
BOOLEAN = "BOOLEAN"
NUMBER = "NUMBER"
STRING = "STRING"
NULL = "NULL"


# parser types
LOG_PARSER_APACHE = "LOG_PARSER_APACHE"
LOG_PARSER_PROXY = "LOG_PARSER_PROXY"
LOG_PARSER_HW = "LOG_PARSER_HW"
